config/routes.rb
Nexus::Application.routes.draw do
  resources :requirement_priorities

  resources :project_services

  root :to => "projects#index"
  
  resources :projects do
    resources :requirements
  end
  
  resources :requirement_types
  resources :users
  resource :session
  
  match "/login" => "sessions#new", :as => "login"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/register" => "users#new", :as => "register"
  

end

app/models/project_service.rb
class ProjectService < ActiveRecord::Base
  has_and_belongs_to_many :projects
end

app/controllers/project_services_controller.rb
class ProjectServicesController < ApplicationController
  # GET /project_services
  # GET /project_services.json
  def index
    @project_services = ProjectService.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @project_services }
    end
  end

  # GET /project_services/1
  # GET /project_services/1.json
  def show
    @project_service = ProjectService.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @project_service }
    end
  end

  # GET /project_services/new
  # GET /project_services/new.json
  def new
    @project_service = ProjectService.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @project_service }
    end
  end

  # GET /project_services/1/edit
  def edit
    @project_service = ProjectService.find(params[:id])
  end

  # POST /project_services
  # POST /project_services.json
  def create
    @project_service = ProjectService.new(params[:project_service])

    respond_to do |format|
      if @project_service.save
        format.html { redirect_to @project_service, :notice => 'Project service was successfully created.' }
        format.json { render :json => @project_service, :status => :created, :location => @project_service }
      else
        format.html { render :action => "new" }
        format.json { render :json => @project_service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /project_services/1
  # PUT /project_services/1.json
  def update
    @project_service = ProjectService.find(params[:id])

    respond_to do |format|
      if @project_service.update_attributes(params[:project_service])
        format.html { redirect_to @project_service, :notice => 'Project service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @project_service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /project_services/1
  # DELETE /project_services/1.json
  def destroy
    @project_service = ProjectService.find(params[:id])
    @project_service.destroy

    respond_to do |format|
      format.html { redirect_to project_services_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/project_services_helper.rb
module ProjectServicesHelper
end

app/views/project_services/_form.html.erb
<%= form_for(@project_service) do |f| %>
  <% if @project_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_service.errors.count, "error") %> prohibited this project_service from being saved:</h2>

      <ul>
      <% @project_service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_services/edit.html.erb
<h1>Editing project_service</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_service %> |
<%= link_to 'Back', project_services_path %>

app/views/project_services/index.html.erb
<h1>Listing project_services</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_services.each do |project_service| %>
  <tr>
    <td><%= project_service.name %></td>
    <td><%= link_to 'Show', project_service %></td>
    <td><%= link_to 'Edit', edit_project_service_path(project_service) %></td>
    <td><%= link_to 'Destroy', project_service, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project service', new_project_service_path %>

app/views/project_services/new.html.erb
<h1>New project_service</h1>

<%= render 'form' %>

<%= link_to 'Back', project_services_path %>

app/views/project_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project_service.name %>
</p>


<%= link_to 'Edit', edit_project_service_path(@project_service) %> |
<%= link_to 'Back', project_services_path %>