config/routes.rb
Nexus::Application.routes.draw do
  resources :requirement_priorities

  resources :project_services

  root :to => "projects#index"
  
  resources :projects do
    resources :requirements
  end
  
  resources :requirement_types
  resources :users
  resource :session
  
  match "/login" => "sessions#new", :as => "login"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/register" => "users#new", :as => "register"
  

end

app/controllers/requirement_types_controller.rb
class RequirementTypesController < ApplicationController
  # GET /requirement_types
  # GET /requirement_types.json
  def index
    @requirement_types = RequirementType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @requirement_types }
    end
  end

  # GET /requirement_types/1
  # GET /requirement_types/1.json
  def show
    @requirement_type = RequirementType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @requirement_type }
    end
  end

  # GET /requirement_types/new
  # GET /requirement_types/new.json
  def new
    @requirement_type = RequirementType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @requirement_type }
    end
  end

  # GET /requirement_types/1/edit
  def edit
    @requirement_type = RequirementType.find(params[:id])
  end

  # POST /requirement_types
  # POST /requirement_types.json
  def create
    @requirement_type = RequirementType.new(params[:requirement_type])

    respond_to do |format|
      if @requirement_type.save
        format.html { redirect_to @requirement_type, :notice => 'Requirement type was successfully created.' }
        format.json { render :json => @requirement_type, :status => :created, :location => @requirement_type }
      else
        format.html { render :action => "new" }
        format.json { render :json => @requirement_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /requirement_types/1
  # PUT /requirement_types/1.json
  def update
    @requirement_type = RequirementType.find(params[:id])

    respond_to do |format|
      if @requirement_type.update_attributes(params[:requirement_type])
        format.html { redirect_to @requirement_type, :notice => 'Requirement type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @requirement_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /requirement_types/1
  # DELETE /requirement_types/1.json
  def destroy
    @requirement_type = RequirementType.find(params[:id])
    @requirement_type.destroy

    respond_to do |format|
      format.html { redirect_to requirement_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/requirement_types_helper.rb
module RequirementTypesHelper
end

app/views/requirement_types/_form.html.erb
<%= form_for(@requirement_type) do |f| %>
  <% if @requirement_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@requirement_type.errors.count, "error") %> prohibited this requirement_type from being saved:</h2>

      <ul>
      <% @requirement_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br />
    <%= f.text_field :abbreviation %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requirement_types/edit.html.erb
<h1>Editing requirement_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @requirement_type %> |
<%= link_to 'Back', requirement_types_path %>

app/views/requirement_types/index.html.erb
<h1>Listing requirement_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Abbreviation</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requirement_types.each do |requirement_type| %>
  <tr>
    <td><%= requirement_type.name %></td>
    <td><%= requirement_type.abbreviation %></td>
    <td><%= requirement_type.description %></td>
    <td><%= link_to 'Show', requirement_type %></td>
    <td><%= link_to 'Edit', edit_requirement_type_path(requirement_type) %></td>
    <td><%= link_to 'Destroy', requirement_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Requirement type', new_requirement_type_path %>

app/views/requirement_types/new.html.erb
<h1>New requirement_type</h1>

<%= render 'form' %>

<%= link_to 'Back', requirement_types_path %>

app/views/requirement_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @requirement_type.name %>
</p>

<p>
  <b>Abbreviation:</b>
  <%= @requirement_type.abbreviation %>
</p>

<p>
  <b>Description:</b>
  <%= @requirement_type.description %>
</p>


<%= link_to 'Edit', edit_requirement_type_path(@requirement_type) %> |
<%= link_to 'Back', requirement_types_path %>