config/routes.rb
Nexus::Application.routes.draw do
  resources :requirement_priorities

  resources :project_services

  root :to => "projects#index"
  
  resources :projects do
    resources :requirements
  end
  
  resources :requirement_types
  resources :users
  resource :session
  
  match "/login" => "sessions#new", :as => "login"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/register" => "users#new", :as => "register"
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :project_services
  has_and_belongs_to_many :users
  has_many :requirements
  
  def requirements_approved
    total = requirements.count
    return 0 if total < 1
    
    approved = requirements.where(approved: true).count
      (approved.to_f / total * 100).round
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.projects.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, :notice => 'Project was successfully created.' }
        format.json { render :json => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, :notice => 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label "Project Services:" %> </br>
    <% for project_service in ProjectService.all %>
      <%= check_box_tag "project[project_service_ids][]", project_service.id, @project.project_service_ids.include?(project_service.id), :id => dom_id(project_service) %>
      <%= label_tag dom_id(project_service), project_service.name, :class => "check_box_label" %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label "Project Staff:" %></br>
    <%= hidden_field_tag "project[user_ids][]", nil %>
    <% for user in User.all %>
      <%= check_box_tag "project[user_ids][]", user.id, @project.user_ids.include?(user.id), :id => dom_id(user) %>
      <%= label_tag dom_id(user), user.full_name, :class => "check_box_label" %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to project.name, project %></td>
    <td><%= project.description %></td>
    <td><%= project.start_date %></td>
    <td><%= project.end_date %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Project Services:</b>
  <% @project.project_services.each do |project_service| %>
    <%= project_service.name %> -
  <% end %>
</p>

<p>
  <b>Project Staff:</b>
  <% @project.users.each do |user| %>
    <%= user.full_name %> -
  <% end %>
</p>

<p>
  <b>Start date:</b>
  <%= @project.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @project.end_date %>
</p>

<p>
  <b>Requirements Approved:</b>
  <%= @project.requirements_approved %>%
</p>

<div id="requirements_display">
<h3>Project Requirements</h3>
  <%= render @project.requirements %>
</div>

<div id="requirements_module">
<h3>Add New Requirement</h3>
<%= render :file => "requirements/new" %>
</div>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>