config/routes.rb
Nexus::Application.routes.draw do
  resources :requirement_priorities

  resources :project_services

  root :to => "projects#index"
  
  resources :projects do
    resources :requirements
  end
  
  resources :requirement_types
  resources :users
  resource :session
  
  match "/login" => "sessions#new", :as => "login"
  match "/logout" => "sessions#destroy", :as => "logout"
  match "/register" => "users#new", :as => "register"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nexus</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
  <h1><%= link_to "Nexus", root_path %></h1><h5>for <span class="huge">Huge</span></h5>
  <div id="user_bar">
    <% if logged_in? %>
      <%= link_to "Projects", projects_path %>
      <%= link_to "Users", users_path %>
      <%= link_to "Edit Account", edit_user_path(current_user) %>
      <%= link_to "Logout", logout_path %>
    <% else %>
      <%= link_to "Login", login_path %>
      <%= link_to "Register", register_path %>
    <% end %>
  </div>
</div>
<div id="main">
  <%= content_tag(:p, notice, :class => "notice") if notice.present? %>
  <%= content_tag(:p, alert, :class => "alert") if alert.present? %>


<%= yield %>
</div>
<div id="footer">
  A prototype project for process management at Huge, by <a href="http://twitter.com/justinraczak">Justin Raczak</a>.
</div>
</body>
</html>